# -*- coding: utf-8 -*-
"""togle2sentence

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ib2_n1QnkETYwX11BTzAwRXbsh0FyjKB

### Query 작성
"""

togle = ["boy", "black", "short hair", "dark colored", "short sleeve shirt", "dark colored", "short pants"]
gender_and_age, hair_color, hair, top_color, top_type, bottom_color, bottom_type = togle
bag = "backpack"

if gender_and_age == "man" or gender_and_age == "boy":
    gender = "He"
else:
    gender = "She"

query = ""

# pants의 경우 a pair of {color} pants와 그냥 {color} pants 중 어떤 게 성능이 더 나을지 확인해봐야 할 듯
# 만약 후자가 더 성능이 잘 나오면 여기서 굳이 경우를 나누지 않아도 됨
if bottom_type == "skirt":
    query += f"A {gender_and_age} wearing a {top_color} {top_type} and a {bottom_color} {bottom_type}. "
else:
    query += f"A {gender_and_age} wearing a {top_color} {top_type} and a pair of {bottom_color} {bottom_type}. "

# 가방을 손에 쥔 거랑 등에 맨 거? 이렇게 나눠도 좋을 듯 (holding ↔ carrying)
if bag == "backpack":
    query += f"{gender} has {hair_color} {hair}. {gender} is carrying a {bag}."
elif bag == "bag":
    query += f"{gender} has {hair_color} {hair}. {gender} is holding a {bag}."
else:
    query += f"{gender} has {hair_color} {hair}."

print(query)

"""### 번역"""

!pip install openai

import openai

OPENAI_API_KEY = ""  # openAI-API 키를 넣으세요
openai.api_key = OPENAI_API_KEY

def translate_english_to_korean(text):
    response = openai.chat.completions.create(
    model = "gpt-3.5-turbo",
    presence_penalty = 0.9,
    messages = [
            {"role": "system", "content": """
            You are a translator.
            I will provide you with the information of the character's description in English, so please translate this information into Korean correctly.

            An example is as follows.

            Case 1.
            Input sentence: A woman wearing a blue long sleeve shirt and a pair of white short pants. She has long hair. He is holding a bag.
            Desired Translation: 긴 머리. 파란색 긴팔 셔츠와 흰 반바지를 입고, 가방을 들고 있음.

            Case 2.
            Input sentence: A boy wearing a black long sleeve shirt and a pair of black long pants. He has long hair.
            Desired Translation: 긴 머리. 검정 긴팔 셔츠와 검정 긴 바지를 입고 있음.

            Case 3.
            Input sentence: A girl wearing a red long sleeve shirt and a white skirt. She has short hair. She is carrying a backpack.
            Desired Translation: 짧은 머리. 빨간 긴팔 셔츠와 흰 치마를 입고, 가방을 메고 있음.

            Case 4.
            Input sentence: A man wearing a dark colored short sleeve shirt and a pair of light colored long pants. He has white short hair. He is carrying a backpack.
            Desired Translation: 짧은 흰 머리. 어두운 반팔 셔츠와 밝은 긴 바지를 입고, 가방을 메고 있음.

            Case 5.
            Input sentence: A boy wearing a light colored short sleeve shirt and a pair of light colored short pants. He has blond short hair. He is holding a backpack.
            Desired Translation: 짧은 금발 머리. 밝은 반팔 셔츠와 반바지를 입고, 가방을 들고 있음.

            Please respond to every sentence simply.
            """},
            {"role": "user", "content": text},
    ]
    )

    return response.choices[0].message.content

english_text = query
korean_text = translate_english_to_korean(english_text)
print("Eng query: ", english_text)
print("Kor query: ", korean_text)

